package com.libertex.wallet.entity;

import io.swagger.annotations.ApiModelProperty;
import lombok.Data;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import java.util.List;

@Data
@Entity
@Table(name = "client")
public class ClientEntity {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty(value = "Client Id (autogenerated)")
    private Long id;

    @Column(name="name")
    @ApiModelProperty(value = "Customer name")
    private String name;

    @OneToMany(cascade = CascadeType.ALL, mappedBy = "id")
    private List<WalletEntity> wallet;
}
