package com.libertex.wallet.entity;

import io.swagger.annotations.ApiModelProperty;
import lombok.Data;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.validation.constraints.Digits;
import javax.validation.constraints.PositiveOrZero;
import java.math.BigDecimal;

@Data
@Entity
@Table(name = "wallet")
public class WalletEntity {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty(value = "Wallet Id (autogenerated)")
    private Long id;

    @PositiveOrZero
    @Digits(integer=20, fraction=2)
    @Column(name="money", nullable = false, precision = 20, scale = 2)
    @ApiModelProperty(value = "Money in wallet")
    private BigDecimal money;

    @ManyToOne
    @JoinColumn(name = "id_client", referencedColumnName = "id")
    private ClientEntity client;
}
